/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package helloworld.jenkins;

public class Library {
    public boolean someLibraryMethod() {
    	System.out.println("Pull request Testing Cibin");
        return true;
    }
}
